---
- hosts: all
  gather_facts: no
  
  tasks:
  - name: CHECKCPUUSAGE
    shell: top -b -n1 | grep -Po '[0-9.]+ id' | awk '{print 100-$1}'
    register: result
  - debug:
      msg: "startFileCpuUsage {{ result.stdout }}endFile"
