---
- hosts: all
  gather_facts: no

  tasks:
    - name: start service httpd,
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ service_list }}"

      register: result
      
    - debug:
        msg: "{{result.stdout}}"
        

  