---
- hosts: all
  gather_facts: no

  tasks:
  - name: Create Directory
    file:
      path: /home/imadmin/
      state: directory
  
  tasks:    
  - name: Create Directory backup folder
    file:
      path: /home/imadmin/backup
      state: directory 
  
  tasks:    
  - name: COPY FILE to host svr(cleanLogFile.sh) 
    copy:
      src: /home/cleanLogFile.sh
      dest: /home/imadmin/cleanLogFile.sh
      owner: imadmin
      mode: u=rwx,g=rwx,o=rwx


  tasks:
  - name: RUN cleanLogFile.sh FILE 
    shell: sh /home/imadmin/cleanLogFile.sh
    register: result
  - debug: var=result
  
  
  tasks:
  - name: RESULT 
    shell: ls /home/imadmin/backup /home/imadmin/backup
    register: result2
  - debug: var=result2.stdout_lines
